## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false

# comment the following lines to disallow failures on nightly julia
matrix:
  allow_failures:
  - julia: nightly
